export { default as GoogleIcon } from './GoogleIcon'
export { default as WavesIcon } from './WavesIcon'
export { default as ValidIcon } from './ValidIcon'
export { default as DotsIcon } from './DotsIcon'
export { default as EyeIcon } from './EyeIcon'
