export { default as blurredBackground } from './blurred-background.jpg'
export { default as georgianFlag } from './georgian-flag.png'
export { default as cardSchedule } from './card-schedule.png'
export { default as britainFlag } from './britain-flag.png'
export { default as calendar } from './calendar.jpg'
export { default as profile } from './profile.png'
